### PR TITLE
fix broken URL

### PR DESCRIPTION
**Pull request by hernansr**
www.trinitycore.net is dead

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
I think we should remove that line entirely, because changing it like that will make the link duplicated

**Comment by hernansr** [comment]
You're right, which one should we remove? I think "Automated Documentation" is better than "How to compile"

**Comment by Aokromes** [comment]
no longer needed.

**Comment by KingPin** [comment]
dns issue, cname added for www.

**Pull request closed without merging**
